language: php

php:
  - 7.3

env:
  - CAKE_VERSION=2.3.10
  - CAKE_VERSION=2.5.4
  #- CAKE_VERSION=master
  #- CAKE_VERSION=2.4.10 (not working with Lib/ElasticSearchRequest for some reason)

install:
  - git clone git://github.com/cakephp/cakephp ../cakephp && cd ../cakephp && git checkout $CAKE_VERSION
  - cp -R ../Icing plugins/Icing
  - cp ../Icing/Config/elastic_search_request.php.default app/Config/elastic_search_request.php
  - chmod -R 777 ../cakephp/app/tmp
  - sh -c "composer global require 'phpunit/phpunit=3.7.33'"
  - sh -c "ln -s ~/.composer/vendor/phpunit/phpunit/PHPUnit ../cakephp/vendors/PHPUnit"

before_script:
  - sh -c "mysql -e 'CREATE DATABASE cakephp_test;'"
  - echo "<?php
    class DATABASE_CONFIG {
    public \$test = array(
      'datasource' => 'Database/Mysql',
      'database' => 'cakephp_test',
      'host' => '0.0.0.0',
      'login' => 'travis',
      'persistent' => false,
    );
    }" > ../cakephp/app/Config/database.php

script:
  - ./lib/Cake/Console/cake test Icing AllTests --stderr

services:
  - redis-server
  - elasticsearch

notifications:
  email: false
